### ISSUE TITLE
Unable to enter more than 3 digits in input when trying to transfer BSV-20

### ISSUE THREAD

**Issue by danwag06** [yours-org/yours-wallet#112]
An example would be sending 100 works but the input deletes everything if you try to send 1000.

**Comment by danwag06** [comment]
@zhfnjust Can you take a look at this one please?

**Comment by zhfnjust** [comment]
@danwag06 fixed by [PR](https://github.com/Panda-Wallet/panda-wallet/pull/117)

cause by this: https://github.com/Panda-Wallet/panda-wallet/commit/7e496cfab733f371d6193a1838d696824d3819fd#r131979035

**Comment by danwag06** [comment]
yep... my bad
