### ISSUE TITLE
add tests and CI

### ISSUE THREAD

**Issue by xhliu** [yours-org/yours-wallet#121]
Once a testing framework is set up, contributors can add their own test cases, which can be put in a CI like Travis or Github Action.

**Comment by danwag06** [comment]
@xhliu would you guys mind tackling this one?

**Comment by xhliu** [comment]
We are not familiar with plugin testing. If you, or someone more familiar, can integrate a testing framework, we are happy to add tests into it.

**Comment by danwag06** [comment]
This was completed in OD hackathon and will be merged.
