### ISSUE TITLE
purchaseOrdinal function assumes use of marketplaceRate and marketplaceAddress

### ISSUE THREAD

**Issue by jdh7190** [yours-org/yours-wallet#125]
At https://github.com/Panda-Wallet/panda-wallet/blob/a7eeb36c2eec1fa9d82b725c817d8154d1a3b42c/src/hooks/useOrds.ts#L690

The logic assumes a marketplace address and fee, if a marketplaceFee of zero is specified, the function returns an error.

If we choose to not charge fees, I would like this output to not be created so markets can choose not to take a fee if they wish.

**Comment by danwag06** [comment]
As it stands, if those params are not supplied it defaults to going to the Panda Dev wallet which is used to fund contributors. Happy to remove it if others agree it should be removed...
