### ISSUE TITLE
Cannot upload 1sat json into Firefox Extension

### ISSUE THREAD

**Issue by jdh7190** [yours-org/yours-wallet#133]
If I try to import json file from the Firefox extension, the extension closes and confirming the upload of the file (Windows) never does anything.

**Comment by jadwahab** [comment]
Hmm that's strange, I only tested it on Mac since I don't have access to Windows. Does the extension load when you click on manifest.json or does it not even get loaded?

Btw make sure you click on manifest.json not asset-manifest.json

**Comment by jdh7190** [comment]
The extension works fine otherwise, I am specifically referring to uploading a json file.

**Comment by mak1986** [comment]
It doesn't work with Chrome either. Once the JSON file is selected the main window closes as well.
