### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by jadwahab** [yours-org/yours-wallet#15]
Would love to see this browser wallet work on Firefox as well. Will try to work on this when I get some free time!

**Comment by jadwahab** [comment]
Just submitted to firefox addons store

![Image](https://github.com/Panda-Wallet/panda-wallet/assets/15110087/7286e6b6-6a04-4e66-8a94-ac3af7777bce)

**Comment by flolu** [comment]
@danwag06 why did you close this as completed? As far as I can see, it's not completed at all. Is there any chance this will be re-prioritized?

**Comment by danwag06** [comment]
This ticket was from years ago and we cleaned a bunch of stale tickets up that no longer applied to BRC-100 update. It's possible this got lost in the mix. Feel free to reopen or submit a PR @flolu

**Comment by flolu** [comment]
@danwag06 understood. Created a new issue: https://github.com/yours-org/yours-wallet/issues/321
