### ISSUE TITLE
Runtime errors in dev mode

### ISSUE THREAD

**Issue by freedomhero** [yours-org/yours-wallet#16]
I attempted to run the project in development mode with the command `npm run start`. The page displayed the following runtime errors after the mnemonic was confirmed:

<img width="1910" alt="image" src="https://github.com/Panda-Wallet/panda-wallet/assets/564244/cfe382d2-e747-4856-b9a0-165f43bc5cf4">

system version: Mac OS 13.4.1 
chrome version: 117.0.5938.149 (x86_64)

**Comment by danwag06** [comment]
Did you load the unpacked build file in chrome extensions? I'm thinking it has something to do with the background.js file in a local env if it's not actually running in chrome.

**Comment by danwag06** [comment]
There's also some more context here... 

https://discord.com/channels/1160086738958565426/1160086739419934731/1160656573622915182

Invite Link if needed: https://discord.gg/qHs6hTkmsf
