### ISSUE TITLE
a lot of compile error when run npm start

### ISSUE THREAD

**Issue by zhfnjust** [yours-org/yours-wallet#17]
![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/24855bd6-ef07-4186-9bdd-9277ce76ecbf)

![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/7747337d-4404-476a-a4e0-3eadcf36ab21)

**Comment by danwag06** [comment]
You ran npm install first?

If so can you confirm bsv package version? Should be 1.5.6

**Comment by danwag06** [comment]
Also curious if anyone else is seeing this behavior. I have not noticed this.

**Comment by zhfnjust** [comment]
> You ran npm install first?
> 
> If so can you confirm bsv package version? Should be 1.5.6

yes, i change nothing. already npm install

**Comment by zhfnjust** [comment]
![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/be637b1f-e33c-4c06-b205-6d13688228e3)
three parameters should failed:
![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/fd65d2e0-79f0-4b60-b5b8-64d5bdf5cea2)

**Comment by danwag06** [comment]
@zhfnjust if you pull down the latest this should be addressed. We're now using `bsv-wasm-web` instead of the legacy `bsv` lib which is missing type definitions. Let me know if the issue is fixed.

**Comment by zhfnjust** [comment]
This is caused by using the wrong bsv version. Version 1.5.6 does not have an index.d.ts declaration file, so no error is reported.
