### ISSUE TITLE
emit when switching network

### ISSUE THREAD

**Issue by gitzhou** [yours-org/yours-wallet#176]
Hi team,

Would it be possible to support emitting signals when switching the network in the wallet?

It would be great if a front-end app could be notified when the wallet network is changed. 😄

**Comment by danwag06** [comment]
It looks like this was originally fixed but would need to be re-introduced after v4.0.0 release as it only supports emitting `switchAccount` and `signedOut` events

**Comment by danwag06** [comment]
@gitzhou After looking into this, in v4.0+ this doesn't apply as the notion of switching networks no longer exists. Instead, you can listen for the `switchAccount` event and then call getNetwork() or look at the address format to determine if the address is `mainnet` or `testnet`.

https://app.gitbook.com/o/k6HnSOibnJKs9gyXDEwI/s/8h5PbVdOLZTSAZHevtG0/the-basics/events
