### ISSUE TITLE
Doesnt support recursive ordinals

### ISSUE THREAD

**Issue by zpxp** [yours-org/yours-wallet#209]
![image](https://github.com/Panda-Wallet/panda-wallet/assets/53557348/05f51724-5042-4021-9791-077f9805d592)

Ordinals using html recursion dont show up in the extension

Here is an example https://whatsonchain.com/tx/ae04e14c7535afc1a103f58378195a409ba0dcec22c1c180bf31f5e0069f4ba4

**Comment by danwag06** [comment]
This has been completed with v4.0
