### ISSUE TITLE
i sent my bsv to my ordinal adress

### ISSUE THREAD

**Issue by Akagami112** [yours-org/yours-wallet#224]
Hi i did a mistake, i sent my bsv to my ordinal adress, could you help me to recovery  please?

Thank you

**Comment by AwesomeKalin** [comment]
It's quite easy to recover it. If you use a mnemonic, simply re-import the wallet, but change the BSV mnemonic derivation path to the one for ordinals. Then send the exact amount that you accidentally sent to the ordinal address, -1 to cover transaction fees. To be on the safe side, you may want to transfer your ordinals to another wallet temporarily

**Comment by danwag06** [comment]
This will also automatically fix itself with v4.0 release.
