### ISSUE TITLE
Allow sending funds to multiple addresses (multiple outputs)

### ISSUE THREAD

**Issue by boecklim** [yours-org/yours-wallet#238]
Hello

As a new feature it would be quite useful (at least for me) if I could create transactions in Yours wallet which don't send funds to only one address but multiple.

I'd imagine a +-button where I can add more recipient addresses.

Cheers

Michael

**Comment by kuopassa** [comment]
Maybe by detecting newlines the UI creates new input fields after checking if addresses look valid.

**Comment by danwag06** [comment]
Internally the wallet already supports this (ie. you can call `sendBSV` via the provider and pass in an array). [See this](https://app.gitbook.com/o/k6HnSOibnJKs9gyXDEwI/s/8h5PbVdOLZTSAZHevtG0/the-basics/send-bsv). However, I understand the request to be able to handle this within the UI/UX as well.

Once we get v4.0 pushed I will try to organize some of these requests.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/yours-wallet).

### My background and how it can be leveraged
I have extensive experience working on multiple projects with TypeScript and JavaScript. I've also contributed to the OnlyDust platform. You can view my profile here: https://app.onlydust.com/u/devcollinss.

**Comment by nafkem** [comment]
Could I grab this task?
