### ISSUE TITLE
Error unlocking coins with imported RelayX wallet.

### ISSUE THREAD

**Issue by redeel-media** [yours-org/yours-wallet#248]
No matching route for selected menu item.

> Stack Trace
> main.js:337 (anonymous function)
> main.js:2 (nl)
> main.js:2 (kc)
> main.js:2 (anonymous function)
> main.js:2 (k)
> main.js:2 (j)

![Screenshot 2024-10-04 195323](https://github.com/user-attachments/assets/bf15c71f-f15c-49b0-8d2e-f1479068b4e6)

**Comment by danwag06** [comment]
@shruggr any ideas on what this may be?

**Comment by danwag06** [comment]
I tried importing a relay x wallet that has some locked coins and am getting a missing inputs error. Also seeing this which we haven't seen @shruggr ....

<img width="823" alt="Screenshot 2024-10-04 at 8 58 11 PM" src="https://github.com/user-attachments/assets/37a881c9-1e4c-4700-9cba-bf47fa571c43">

**Comment by danwag06** [comment]
This has been addressed.
