### ISSUE TITLE
Select and send/list multiple ordinals at the same time

### ISSUE THREAD

**Issue by danwag06** [yours-org/yours-wallet#250]
It would be nice to be able to select and send (or even list for sale) many ordinals in a single transaction. When trying to move many assets, it can be tedious to do this one-by-one.

**Comment by CHIRAG-021** [comment]
can i do it?

**Comment by danwag06** [comment]
@CHIRAG-021 It's an open source project. Feel free to open a PR. We will review it.

**Comment by danwag06** [comment]
This was handled via BSVA hackathon.
