### ISSUE TITLE
Can't sign with Panda wallet

### ISSUE THREAD

**Issue by Neggia** [yours-org/yours-wallet#44]
Hello,
here https://github.com/Neggia/test-panda I created a sample application you can run locally (first run npx scrypt-cli@latest compile , then npm start), the issue is the following:
- Logging with TAAL/Panda wallets you can Send amount to contract TestPanda and it gets correctly signed on both
- Logging with TAAL wallet you can Send amount to contract TestPanda2 and it gets correctly signed, but not with Panda wallet (bundle.js:131 Error: WhatsonchainProvider ERROR: Script evaluation failed.)
- The only contracts difference in \src\contracts are the lines commented with /* ... */ , you can get the hex in the \artifacts folder in json files property hex.
You can download TAAL wallet here https://chrome.google.com/webstore/detail/taal-wallet/engokokaoeppkmchbkjeoeimiffobcke

**Comment by danwag06** [comment]
@xhliu or @zhfnjust can you guys take a look at this?

**Comment by zhfnjust** [comment]
@Neggia bsv-wasm have some issue when signing, i am fixing this.

**Comment by zhfnjust** [comment]
a pr to fix this, wait it be merge.

https://github.com/Firaenix/bsv-wasm/pull/64

**Comment by zhfnjust** [comment]
Since the PR is still not merged, we provide a locally compiled version to solve this problem. You can download and install it. 

https://github.com/sCrypt-Inc/panda-wallet/releases/tag/lastest

DM me if any Questions

@Neggia @xhliu

**Comment by Neggia** [comment]
Can sign correctly now, thanks a lot

**Comment by danwag06** [comment]
@zhfnjust can you open a PR to get these changes merged to main?

**Comment by zhfnjust** [comment]
@danwag06 the pr still not merged, https://github.com/Firaenix/bsv-wasm/pull/64,
it need to pump bsv-wasm

**Comment by zhfnjust** [comment]
Since the PR is still not merged, I suggest using the locally compiled bsv-wasm library to solve this problem. Waiting for bsv-wasm to really solve this problem, we are re-using the online version.

this PR #91 use  locally compiled bsv-wasm library

**Comment by zhfnjust** [comment]
@danwag06

**Comment by zhfnjust** [comment]
@danwag06 

I found that the latest releases of panda still have this problem, but when I try to load my locally compiled panda, it works fine. So I also suspect there is something wrong with your local environment. You can try to delete `node_modules` and then recompile. Then give me the zip file to verify?

**Comment by zhfnjust** [comment]
Looks like you are using the wrong wasm file：

![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/3046c6e1-133f-47e3-b65d-f2afef20a2c6)

**Comment by zhfnjust** [comment]
The result of packaging should be to use this file

`bsv\bsv-wasm-web\bsv_wasm_bg.wasm`

**Comment by danwag06** [comment]
@zhfnjust this is a build of `main` after deleting package.json and package-lock.json and reinstalling

[build.zip](https://github.com/Panda-Wallet/panda-wallet/files/13283411/build.zip)

**Comment by zhfnjust** [comment]
perfect now!
