### ISSUE TITLE
support  Implied Transfers Deprecated

### ISSUE THREAD

**Issue by zhfnjust** [yours-org/yours-wallet#67]
I just tested with a number of transfers. It appears to work well in most scenarios, but has an issue with tokens which were previously transferred with `implied` transfers. Implied transfers are no longer valid for new transfers, but are supported for transfers before block 800000, or something like that.

With an implied transfer, there is no transfer inscription, so you can't parse the bsv20 from the inscription and you need to get the data from the indexer. There are currently 953 implied outpoints in existence across 82 different addresses. `implied: true` is returned in the TxoData for these txos.

For users with implied transfer outpoints, transfer of that ticker will likely break, as it did for me.

_Originally posted by @shruggr in https://github.com/Panda-Wallet/panda-wallet/issues/65#issuecomment-1783525799_

**Comment by danwag06** [comment]
@shruggr is this still an issue with the change you made in #119 ?

**Comment by shruggr** [comment]
Nope. This is resolved now
