### ISSUE TITLE
Any reason for non-standard bip44 key derivation scheme?

### ISSUE THREAD

**Issue by jadwahab** [yours-org/yours-wallet#7]
Any specific reason for using a non-standard bip44 key derivation scheme here? https://github.com/Panda-Wallet/panda-wallet/blob/main/src/utils/keys.ts#L17

bip44 spec https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

registered coin types https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by danwag06** [comment]
@jadwahab nope, it worked so I went with it. I'd prefer for the wallet to follow whatever standards exist. I made an assumption that it didn't matter. I needed two different keys from the same mnemonic. My knowledge is limited at this lower level so if you want to open a PR that follows the standard it would be appreciated!

**Comment by danwag06** [comment]
@jadwahab I dug into this a bit. Would the suggestion be to do something like the following?

BSV Address: `m / 44' / 236' / 0' / 0 / 0`
Ord Address: `m / 44' / 236' / 1' / 0 / 0`

**Comment by jadwahab** [comment]
@danwag06 standard bip44 would probably be on the account level, so:

BSV Address: `m / 44' / 236' / 0' / 0 / 0`
Ord Address: `m / 44' / 236' / 0' / 1 / 0`

But anyway most important thing is to make it clear what your wallet uses exactly

**Comment by danwag06** [comment]
@jadwahab hmm... what am I missing or did I have it right? This is from the spec...

<img width="602" alt="Screen Shot 2023-10-04 at 2 13 35 PM" src="https://github.com/Panda-Wallet/panda-wallet/assets/25462225/fd3dfc2a-062b-47aa-bfec-9a9ded0d8976">

**Comment by jadwahab** [comment]
@danwag06 Ah yes you did have it right, my bad.
