### ISSUE TITLE
`wallet.getOrdinals()` returns empty array

### ISSUE THREAD

**Issue by msinkec** [yours-org/yours-wallet#81]
The result of the `getOrdinals` function returns an empty array, even though my wallet contains multiple, which also show up correctly in the extension.

I've only tried in testnet mode. I didn't try mainnet.

**Comment by danwag06** [comment]
@msinkec this could be a bug in testmode. I am not seeing any issues in mainnet. 

Would you mind trying in main to make sure it's not isolate to your wallet?

**Comment by danwag06** [comment]
Also, make sure that before you call `getOrdinals` that `isConnected` is returning `true`

**Comment by msinkec** [comment]
For some reason its empty for mainnet as well. I'm using 1.3.0 
![image](https://github.com/Panda-Wallet/panda-wallet/assets/44239392/f419ba7a-2682-467d-b4fb-658ce1a7398e)

**Comment by zhfnjust** [comment]
Fixed https://github.com/Panda-Wallet/panda-wallet/pull/105
