### ISSUE TITLE
support Inscribe (mint)  NFT

### ISSUE THREAD

**Issue by zhfnjust** [yours-org/yours-wallet#88]

**Comment by xhliu** [comment]
[Unisat](https://chrome.google.com/webstore/detail/unisat-wallet/ppbibelpcjmhbdihakflkdcoccbgbkpo) supports it.

**Comment by danwag06** [comment]
@xhliu I assume the idea here is to support it within the wallet UI as well as giving devs a way to inscribe via the provider?

**Comment by xhliu** [comment]
I was thinking only of the former, but the latter would be nice too.

**Comment by jdh7190** [comment]
latter doesn't seem necessary as technically is supported by sending to custom scripts as documented here:

https://panda-wallet.gitbook.io/provider-api/the-basics/send-bsv#custom-scripts

Inscribing also doesn't require spending of non-P2PKH inputs (unless re-inscribing which is edge case)

**Comment by danwag06** [comment]
@jdh7190 ... @shruggr and I discussed this and ultimately ended up deciding to abstract inscribe into it's own method (which ultimately uses sendBsv under the hood). This should make it easier for non-bitcoin devs to start inscribing without needing to understand how to build a script from scratch or learn other tooling. cc @xhliu 

This is resolved with #149
