### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by zhfnjust** [yours-org/yours-wallet#89]
the latest code show below:

![image](https://github.com/Panda-Wallet/panda-wallet/assets/995909/77515572-b920-419d-9f0d-a46d2fdfbcbc)

**Comment by danwag06** [comment]
@zhfnjust is this addressed with #92 or is this something different?

**Comment by zhfnjust** [comment]
something different

**Comment by danwag06** [comment]
@zhfnjust see if #95 addresses the issue. I'm confused as to how a `tick` or `sym` would get that long to begin with. If it does address it... feel free to approve the PR.
